"use client";

import { useMemo, useRef, useState } from "react";
import { parseInventory, type Product } from "@/lib/inventory";

const label = (status: Product["status"]) => status === "DEAD" ? "Dead stock" : status === "AT_RISK" ? "At risk" : "On track";
const tone = (status: Product["status"]) => status === "DEAD" ? "dead" : status === "AT_RISK" ? "risk" : "normal";

export default function Home() {
  const [products, setProducts] = useState<Product[]>([]);
  const [selected, setSelected] = useState<Product | null>(null);
  const [error, setError] = useState("");
  const [answer, setAnswer] = useState("");
  const [question, setQuestion] = useState("");
  const [loading, setLoading] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  const stats = useMemo(() => ({ dead: products.filter(p => p.status === "DEAD").length, risk: products.filter(p => p.status === "AT_RISK").length, normal: products.filter(p => p.status === "NORMAL").length }), [products]);
  const attention = products.filter(p => p.status !== "NORMAL");

  async function load(file: File) { try { setError(""); setAnswer(""); setSelected(null); setProducts(parseInventory(await file.text())); } catch (e) { setProducts([]); setError(e instanceof Error ? e.message : "Could not read this CSV."); } }
  async function demo() { try { const r = await fetch("/demo.csv"); if (!r.ok) throw new Error(); setError(""); setAnswer(""); setSelected(null); setProducts(parseInventory(await r.text())); } catch { setError("Could not load the demo CSV."); } }
  async function ask(prompt: string) { if (!selected) return; setLoading(true); setAnswer(""); setError(""); try { const r = await fetch("/api/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ product: selected, daysSinceLastSale: selected.daysSinceLastSale, status: selected.status, question: prompt }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error ?? "Local AI is unavailable."); setAnswer(data.answer); } catch (e) { setError(e instanceof Error ? e.message : "Local AI is unavailable."); } finally { setLoading(false); } }
  function choose(product: Product) { setSelected(product); setAnswer(""); setQuestion(""); }

  return <main className="app-shell">
    <header className="site-header"><a className="wordmark" href="#top"><span className="mark">D</span><span>Dead Stock <em>Dost</em></span></a><div className="header-meta"><span className="privacy">⌁ Your data stays local</span><span className="ai-status"><i /> Local AI</span></div></header>
    <section className={`hero ${products.length ? "loaded" : ""}`} id="top"><div className="hero-copy"><span className="kicker"><i /> INVENTORY, MADE CLEAR</span><h1>{products.length ? "Here’s where your stock needs a nudge." : <>See what’s waiting <em>too long</em> on the rack.</>}</h1><p>{products.length ? `${attention.length} products need your attention. Start with the oldest items and decide what to try.` : "A calm, local way to spot slow-moving garments before they become forgotten stock."}</p><div className="hero-actions"><button className="button light" onClick={() => input.current?.click()}>{products.length ? "Replace inventory" : "Upload inventory CSV"}<span>→</span></button>{!products.length && <button className="text-button" onClick={demo}>Explore sample shop <span>↗</span></button>}</div><input ref={input} type="file" accept=".csv,text/csv" hidden onChange={e => e.target.files?.[0] && load(e.target.files[0])}/></div><div className="hero-art" aria-hidden="true"><b>LOCAL<br/>FIRST</b><i/><i/><i/></div></section>
    {error && !selected && <div className="notice"><b>!</b>{error}</div>}
    {products.length > 0 ? <><section className="overview"><div className="overview-lead"><span>AT A GLANCE</span><strong>{products.length}</strong><p>pieces<br/>in stock</p></div><Metric type="dead" value={stats.dead} name="Dead stock" note="90+ days" icon="↘"/><Metric type="risk" value={stats.risk} name="At risk" note="45–89 days" icon="!"/><Metric type="normal" value={stats.normal} name="Moving well" note="Under 45 days" icon="✓"/></section>
      <section className="dashboard"><section className="inventory-card"><div className="card-heading"><div><span>THE PRIORITY LIST</span><h2>Needs attention <b>{attention.length}</b></h2></div><p>Oldest unsold first</p></div>{attention.length > 0 ? <><div className="table-head"><span>Product</span><span>Age</span><span>Stock</span><span>Status</span></div><div className="products">{attention.map((product, index) => <ProductRow key={`${product.name}-${index}`} product={product} index={index} active={product === selected} select={choose}/>)}</div></> : <div className="empty"><b>Nothing needs attention right now.</b><p>Every in-stock item has sold within the last 45 days.</p></div>}<details className="all-products"><summary>View the {stats.normal} products that are moving well <span>↓</span></summary><div>{products.filter(p => p.status === "NORMAL").map((product, index) => <ProductRow key={`${product.name}-${index}`} product={product} index={index} active={product === selected} select={choose}/>)}</div></details></section>
        <aside className="insight">{selected ? <><div className="selection-top"><span className={`status ${tone(selected.status)}`}>{label(selected.status)}</span><small>Last sold {selected.lastSaleDate}</small></div><h2>{selected.name}</h2><p className="category">{selected.category} <span>·</span> ₹{selected.price.toLocaleString("en-IN")}</p><div className="spotlight"><div><b>{selected.daysSinceLastSale}</b><span>days without<br/>a sale</span></div><div><b>{selected.stock}</b><span>units still<br/>on hand</span></div></div><div className="why"><b>Why it’s here</b><p>This item has {selected.stock} units left and no recorded sale for {selected.daysSinceLastSale} days.</p></div><div className="ask"><div className="ask-title"><i>✦</i><div><span>ASK YOUR LOCAL AI</span><b>Get a grounded next step</b></div></div><div className="quick"><button onClick={() => ask("Why is this stuck?")} disabled={loading}>Why is this stuck?</button><button onClick={() => ask("What can I try?")} disabled={loading}>What can I try?</button></div><form onSubmit={e => { e.preventDefault(); if (question.trim()) ask(question.trim()); }}><input value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask a specific question..."/><button disabled={!question.trim() || loading}>↑</button></form></div>{loading && <div className="response loading"><i/> Looking at the facts...</div>}{answer && <div className="response"><span>DOST SAYS</span><p>{answer}</p></div>}{error && <div className="ai-error"><b>Local AI unavailable</b><p>{error}</p></div>}</> : <div className="no-selection"><div className="selection-art"><b>✦</b><i/><i/><i/></div><span>YOUR NEXT MOVE</span><h2>Choose a piece from the list.</h2><p>We’ll show why it needs a look, then help you think through what to try.</p><small><b>1</b> Pick an item <b>2</b> See the facts <b>3</b> Ask Dost</small></div>}</aside></section></> : !error && <section className="empty-home"><div className="file-icon">CSV</div><div><span>READY WHEN YOU ARE</span><h2>Bring in your inventory.</h2><p>Use the sample shop to see the full experience, or upload your own CSV with product, stock and last-sale details.</p></div><button className="button dark" onClick={demo}>Try the sample data <span>→</span></button></section>}
    <footer><b>DEAD STOCK DOST</b><span>Small signals. Better shop decisions.</span><em>Made to run locally</em></footer>
  </main>;
}

function Metric({ type, value, name, note, icon }: { type: string; value: number; name: string; note: string; icon: string }) { return <div className={`metric ${type}`}><i>{icon}</i><div><b>{value}</b><span>{name}</span></div><small>{note}</small></div>; }
function ProductRow({ product, index, active, select }: { product: Product; index: number; active: boolean; select: (product: Product) => void }) { return <button className={`product-row ${active ? "selected" : ""}`} onClick={() => select(product)}><i className={tone(product.status)}>{product.status === "NORMAL" ? "✓" : String(index + 1).padStart(2, "0")}</i><span className="product-name"><b>{product.name}</b><small>{product.category} · ₹{product.price.toLocaleString("en-IN")}</small></span><span className="value"><b>{product.daysSinceLastSale}</b><small>days</small></span><span className="value stock"><b>{product.stock}</b><small>units</small></span><span className={`status ${tone(product.status)}`}>{label(product.status)}</span><em>→</em></button>; }
